-- MySQL Script generated by MySQL Workbench
-- Tue May  2 17:38:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NULL,
  `short_name` VARCHAR(5) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`provinces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`provinces` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `short_name` VARCHAR(4) NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_provinces_countries1_idx` (`country_id` ASC),
  CONSTRAINT `fk_provinces_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `npa` INT NULL,
  `name` VARCHAR(250) NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_cities_provinces1_idx` (`province_id` ASC),
  CONSTRAINT `fk_cities_provinces1`
    FOREIGN KEY (`province_id`)
    REFERENCES `mydb`.`provinces` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`streets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`streets` (
  `id` INT NOT NULL,
  `name` VARCHAR(250) NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_streets_cities_idx` (`city_id` ASC),
  CONSTRAINT `fk_streets_cities`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`adresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(5) NULL,
  `line` VARCHAR(250) NULL,
  `street_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_adresses_streets1_idx` (`street_id` ASC),
  CONSTRAINT `fk_adresses_streets1`
    FOREIGN KEY (`street_id`)
    REFERENCES `mydb`.`streets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`titles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `short_name` VARCHAR(5) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `firstname` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `private_phone` VARCHAR(45) NULL,
  `public_phone` VARCHAR(45) NULL,
  `iban` VARCHAR(34) NULL,
  `password` CHAR(128) NULL,
  `reference_number` VARCHAR(45) NULL,
  `adresse_id` INT NOT NULL,
  `title_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_users_adresses1_idx` (`adresse_id` ASC),
  INDEX `fk_users_title1_idx` (`title_id` ASC),
  INDEX `fk_users_roles1_idx` (`role_id` ASC),
  CONSTRAINT `fk_users_adresses1`
    FOREIGN KEY (`adresse_id`)
    REFERENCES `mydb`.`adresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_title1`
    FOREIGN KEY (`title_id`)
    REFERENCES `mydb`.`titles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`buildings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `code_entrance` VARCHAR(45) NULL,
  `adresse_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_buildings_adresses1_idx` (`adresse_id` ASC),
  INDEX `fk_buildings_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_buildings_adresses1`
    FOREIGN KEY (`adresse_id`)
    REFERENCES `mydb`.`adresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_buildings_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`floors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`floors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NULL,
  `building_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_floors_buildings1_idx` (`building_id` ASC),
  CONSTRAINT `fk_floors_buildings1`
    FOREIGN KEY (`building_id`)
    REFERENCES `mydb`.`buildings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lots` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NULL,
  `floor_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_flats_floors1_idx` (`floor_id` ASC),
  INDEX `fk_lots_types1_idx` (`type_id` ASC),
  CONSTRAINT `fk_flats_floors1`
    FOREIGN KEY (`floor_id`)
    REFERENCES `mydb`.`floors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lots_types1`
    FOREIGN KEY (`type_id`)
    REFERENCES `mydb`.`types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`forms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`forms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reference_number` VARCHAR(20) NULL,
  `date_signature` DATETIME NULL,
  `date` DATETIME NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_forms_cities1_idx` (`city_id` ASC),
  CONSTRAINT `fk_forms_cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lot_user_form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lot_user_form` (
  `lot_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `form_id` INT NOT NULL,
  INDEX `fk_flats_has_users_users1_idx` (`user_id` ASC),
  INDEX `fk_flats_has_users_flats1_idx` (`lot_id` ASC),
  INDEX `fk_lotsUsers_forms1_idx` (`form_id` ASC),
  CONSTRAINT `fk_flats_has_users_flats1`
    FOREIGN KEY (`lot_id`)
    REFERENCES `mydb`.`lots` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flats_has_users_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lotsUsers_forms1`
    FOREIGN KEY (`form_id`)
    REFERENCES `mydb`.`forms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rooms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `number` INT NULL,
  `flat_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_rooms_flats1_idx` (`flat_id` ASC),
  CONSTRAINT `fk_rooms_flats1`
    FOREIGN KEY (`flat_id`)
    REFERENCES `mydb`.`lots` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table2` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`signatures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`signatures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `form_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_signatures_forms1_idx` (`form_id` ASC),
  INDEX `fk_signatures_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_signatures_forms1`
    FOREIGN KEY (`form_id`)
    REFERENCES `mydb`.`forms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_signatures_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `number` INT NULL,
  `matter` VARCHAR(100) NULL,
  `comment` VARCHAR(45) NULL,
  `statu_id` INT NULL,
  `room_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_items_status1_idx` (`statu_id` ASC),
  INDEX `fk_items_rooms1_idx` (`room_id` ASC),
  CONSTRAINT `fk_items_status1`
    FOREIGN KEY (`statu_id`)
    REFERENCES `mydb`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_rooms1`
    FOREIGN KEY (`room_id`)
    REFERENCES `mydb`.`rooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`energies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`energies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `metric` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `energiescol_UNIQUE` (`name` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lot_energy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lot_energy` (
  `id` VARCHAR(45) NOT NULL,
  `lot_id` INT NOT NULL,
  `energy_id` INT NOT NULL,
  `number` INT NULL,
  `value` INT NULL,
  INDEX `fk_lots_has_energies_energies1_idx` (`energy_id` ASC),
  INDEX `fk_lots_has_energies_lots1_idx` (`lot_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_lots_has_energies_lots1`
    FOREIGN KEY (`lot_id`)
    REFERENCES `mydb`.`lots` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lots_has_energies_energies1`
    FOREIGN KEY (`energy_id`)
    REFERENCES `mydb`.`energies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
